# This is a basic workflow to help you get started with Actions

name: CI BUILD

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CI"]
    branches:
        - build
    types:
      - completed
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Custom input for Workflow A'
        required: true

jobs:
  get_user_input:
    runs-on: ubuntu-latest

    steps:
      - name: Ask for User Input
        id: input
        run: |
          echo "What is your input?"
          read user_input
          echo "::set-output name=user_input::$user_input"

      - name: Print User Input
        run: |
          echo "User Input: ${{ steps.input.outputs.user_input }}"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world from !

#       # Runs a set of commands using the runners shell
#       # - name: Run a multi-line script
#       #   run: |
#       #     echo Add other actions to build,
#       #     echo test, and deploy your project.
